name: lobbyutils
version: '${version}'
main: dev.c127.lobbyutils.Lobbyutils
api-version: '1.20'
folia-supported: true
softdepend: [PlaceholderAPI]

commands:
  blind:
    description: Just try it
    usage: /<command>